### ISSUE TITLE
USE GOOGLE COLAB

### ISSUE THREAD

**Issue by RohanOpenSource** [TejasOS/MachineLearning#2]
jupyter notebook is DOGWATER. Colab has gpu for MAXIMUM SPEED!!!

**Comment by TejasOS** [comment]
Ok!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
